### ISSUE TITLE
Failed to build the kernel?

### ISSUE THREAD

**Issue by madper** [embeddedTS/ubuntu-kernel#1]
Hi,

I'm trying to build the kernel with following steps:
1. copy ts4900_ubuntucore_defconfig.config to .config
2. make -j8 ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zImage modules imx6q-ts4900.dtb imx6dl-ts4900.dtb

The make goes well but returns 2 as return value. Form the build log I can't find any clue:
```
  LD [M]  sound/core/oss/snd-mixer-oss.ko
  LD [M]  sound/core/oss/snd-pcm-oss.ko
  LD [M]  sound/core/seq/oss/snd-seq-oss.ko
  LD [M]  sound/core/seq/snd-seq-device.ko
  LD [M]  sound/core/seq/snd-seq-midi-event.ko
  LD [M]  sound/core/seq/snd-seq-midi.ko
  LD [M]  sound/core/seq/snd-seq.ko
  LD [M]  sound/core/snd-hwdep.ko
  LD [M]  sound/core/snd-rawmidi.ko
  LD [M]  sound/usb/snd-usb-audio.ko
  LD [M]  sound/usb/snd-usbmidi-lib.ko
  HOSTCC  firmware/ihex2fw
  IHEX2FW firmware/whiteheat_loader.fw
  IHEX2FW firmware/whiteheat.fw
λ  ubuntu-kernel-tsimx6  ts-ubuntu-xenial × echo $?
2
```

And the vmlinux is created already after build failed:

```
λ  ubuntu-kernel-tsimx6  ts-ubuntu-xenial × file vmlinux
vmlinux: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, BuildID[sha1]=6ebbf413a4f4d51226826d1bff0441f08b612b5d, not stripped
```

Do you have any ideas about it?

Thanks a lot in advance,
Madper

**Comment by ts-kris** [comment]
I sincerely apologize for leaving this open for so long. I'm currently working to address all open issues.

I can comment then I was not able to reproduce any issues in building this.
